language: python
python:
  - "2.7"
  # PyPy versions
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0
  - "pypy-5.3.1"
# command to install dependencies
#install:
#  - 
# command to run tests
#script: pytest

sudo: required

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

after_success: |
  pip install --upgrade --user awscli
  aws --version
  ./deploy.sh