language: python
python:
  - "2.7"
# command to install dependencies
install: echo "skip"
# command to run tests
script: echo "skip"

sudo: required

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

after_success: |
  set -e
  pip install --upgrade awscli
  aws --version
  ./deploy.sh