AWSTemplateFormatVersion: 2010-09-09
Description: "Carbcounter lambda function for aws cloudformation package|deploy."
Transform: "AWS::Serverless-2016-10-31"
Resources:
  Lambda:
    # Additional type documentation available at
    # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: carbcounter.lambda_handler
      Runtime: python2.7
      CodeUri: /Users/billyfisher/carbcounter.billyjf.com/lambda/carbcounter
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /carbcounter/{search+}
            Method: get
      Policies:
      - Statement:
        - Effect: Allow
          Action: logs:CreateLogGroup
          Resource: arn:aws:logs:us-west-2:649309545751:*
        - Effect: Allow
          Action:
          - logs:CreateLogStream
          - logs:PutLogEvents
          Resource:
          - arn:aws:logs:us-west-2:649309545751:log-group:/aws/lambda/carbcounter:*
